#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmartTrade.Resource", IsApplication=true)]

namespace SmartTrade
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050002
			public const int LeftPadding = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int RightPadding = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int TopMargin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TopPadding = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_stat_name = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int ApiKey = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int ApiSecret = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int EnableDisableServiceButton = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int LastTradeBalance1TextView = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int LastTradeBalance2TextView = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int LastTradeResultTextView = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int LastTradeTimeTextView = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int Mode = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int NextTradeTimeTextView = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int SectionEndTextView = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int SectionStartTextView = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int SettingsButton = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int TickersListView = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int TradePeriod = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int TransferToMainAccount = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int UserId = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Settings = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SimpleSpinnerDropDownItem = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Status = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060018
			public const int ApiKey = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int ApiSecret = 2131099673;
			
			// aapt resource value: 0x7f060001
			public const int AppDescription = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int AppName = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int Balance = 2131099656;
			
			// aapt resource value: 0x7f060025
			public const int BootNoServiceEnabledPopup = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int BootPopup = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int BoughtPopup = 2131099687;
			
			// aapt resource value: 0x7f06001b
			public const int Buy = 2131099675;
			
			// aapt resource value: 0x7f06000e
			public const int Days = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int End = 2131099661;
			
			// aapt resource value: 0x7f060014
			public const int FutureFix = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int Hours = 2131099663;
			
			// aapt resource value: 0x7f06002b
			public const int InsufficientBalancePopup = 2131099691;
			
			// aapt resource value: 0x7f060012
			public const int JustNow = 2131099666;
			
			// aapt resource value: 0x7f060006
			public const int LastTrade = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int Minutes = 2131099664;
			
			// aapt resource value: 0x7f06001a
			public const int Mode = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int Never = 2131099667;
			
			// aapt resource value: 0x7f06001f
			public const int NeverTransfer = 2131099679;
			
			// aapt resource value: 0x7f06000a
			public const int NextTrade = 2131099658;
			
			// aapt resource value: 0x7f06002a
			public const int NoDepositPopup = 2131099690;
			
			// aapt resource value: 0x7f060026
			public const int NothingToTradePopup = 2131099686;
			
			// aapt resource value: 0x7f060015
			public const int PastFix = 2131099669;
			
			// aapt resource value: 0x7f06000b
			public const int Period = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int Result = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int Seconds = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int Sell = 2131099676;
			
			// aapt resource value: 0x7f060004
			public const int ServiceIsDisabled = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ServiceIsEnabled = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int Settings = 2131099651;
			
			// aapt resource value: 0x7f060016
			public const int SettingsTitle = 2131099670;
			
			// aapt resource value: 0x7f060028
			public const int SoldPopup = 2131099688;
			
			// aapt resource value: 0x7f06000c
			public const int Start = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int StatusTitle = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int Time = 2131099655;
			
			// aapt resource value: 0x7f06001d
			public const int TradePeriod = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int TransferAfterEveryHundredthTrade = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int TransferAfterEveryTenthTrade = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int TransferAfterEveryTrade = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int TransferAfterEveryTradePeriodEnd = 2131099680;
			
			// aapt resource value: 0x7f06001e
			public const int TransferToMainAccount = 2131099678;
			
			// aapt resource value: 0x7f060029
			public const int TransferredPopup = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int UnexpectedErrorPopup = 2131099692;
			
			// aapt resource value: 0x7f060017
			public const int UserId = 2131099671;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
