#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmartTrade.Resource", IsApplication=true)]

namespace SmartTrade
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Bitstamp.Resource.String.ApplicationName = global::SmartTrade.Resource.String.ApplicationName;
			global::Bitstamp.Resource.String.Hello = global::SmartTrade.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int left_padding = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int right_padding = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int top_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int top_padding = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_stat_name = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int api_key = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int api_secret = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int enable_disable_service_button = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int last_trade_balance1_text_view = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int last_trade_balance2_text_view = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int last_trade_result_text_view = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int last_trade_time_text_view = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int next_trade_time_text_view = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int settings_button = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int user_id = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Settings = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int api_key = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int api_secret = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int app_description = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050012
			public const int bought_popup = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int checking_popup = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int done = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int insufficient_balance_popup = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int last_balance = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int last_trade = 2131034119;
			
			// aapt resource value: 0x7f050014
			public const int no_deposit_popup = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int nothing_to_trade_popup = 2131034129;
			
			// aapt resource value: 0x7f050005
			public const int service_is_disabled = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int service_is_disabled_popup = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int service_is_enabled = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int service_is_enabled_popup = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int settings = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int settings_title_format = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int sold_popup = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int unexpected_error_popup = 2131034134;
			
			// aapt resource value: 0x7f05000a
			public const int user_id = 2131034122;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
